### ISSUE TITLE
3' UTR seqlist

### ISSUE THREAD

**Issue by rrydbirk** [muhligs/miReact#1]
Maybe I'm missing something, but if I understand your tutorial correctly, I need to input the 3' UTR seqlist from my own experiment, is that correct? In that case, could you describe how I obtain this from, e.g., 10X experiments (FASTQ or BAM)?
Thanks!

**Comment by muhligs** [comment]
I encourage you to look at the downsampled 'Tabula Muris' data set to get a feel for how the data set should look.

You need the expression matrix as an R matrix object as input. With gene identifiers as ensenble gene IDs (ENSGxxxxx) or gene symbols. The gene IDs or symbols shold be the rownames of the matrix.

The sequences (for human and mouse) are provided in the software. But you need to either download (from synapse) or produce motif probabilities in sequences as instructed in the tutorial under 'Calculating motif probabilities in sequences'.

The reason for this is that the file (R matrix) is too big to be on github (3-4 gb). It is a matrix containing probabilities for observing motifs in the 3'utr sequences.

If you are working in another organism than mouse or human, you will need to obtain the 3'UTR sequences. In that case, I can try to walk you through the process. Let me know.

**Comment by muhligs** [comment]
So to clarify, you need to estimate gene expression from FASTQ or BAM files prior to using this tool.
