### ISSUE TITLE
miReact for Drosophila

### ISSUE THREAD

**Issue by liuyifang** [muhligs/miReact#3]
Awesome tool.

Is there a tutorial that I can obtain the 3'UTR sequences for Drosophila? Thanks!

**Comment by muhligs** [comment]
Hi Liuyifang
Thanks for your comment :)
I have added a pdf in the root that describes the procedure.

**Comment by liuyifang** [comment]
Thanks for your tutorial! I can easily follow the ensembl part.
In the "create a one line fasta file" part, the code was covered because of the pdf format, could you please adjust the command to multiple lines to avoid this issue?

**Comment by muhligs** [comment]
Thanks for noting! Done.

**Comment by liuyifang** [comment]
Thanks! I successfully followed the tutorial and generate the "dm.utr3.seqs.rds" file.
My following question is instead of `seqs` file, how is the `seqlist` rds file generated?

**Comment by liuyifang** [comment]
Thanks for your information! A small typo `regmex` should be `Regmex` in the following code:
`seqlist <- regmex::seq.list.con(seqlist = seqs$sequence, cores=1)`

**Comment by muhligs** [comment]
Thanks for the catches. I have updated.

**Comment by liuyifang** [comment]
In your tutorial, ACACTCC represents the activity for miR-122. How to connect the motif with the miRNA? Does this also apply to Drosophila? Thanks!

**Comment by muhligs** [comment]
This is the complementary bases to the miRNA seed site, here defined as position 2-8 from the 5' end of the miRNA. Bases have been 'translated' from RNA to DNA, i.e. U -->T. As stated in the discussion of the paper, this rule may not apply to all miRNAs in all species. I would think, though. that in general the seed site in Drosophila would look similar to that in vertebrates for like miRNAs. But I think you should use the miRNA sequences from miRbase for Drosophila when deciding which motifs could be targets of a miRNA.

**Comment by muhligs** [comment]
I am closing this issue to bound its scope. You are of course welcome to contact me with additional questions you may have.
Thanks for helping improving the product!
