### ISSUE TITLE
Further information about patterns.7mer.Rdata

### ISSUE THREAD

**Issue by kapka2** [muhligs/miReact#5]
Hi,
Thanks for developing this method and sharing the code.  I'd like to try this approach, however I'd like to understand a bit further about the processing of the motifs.  I see that miReact analysis is based on having an existing patterns list which is loaded from the file patterns.7mer.Rdata.  Would it be possible to share how this list was generated?  Also, is there any documentation of the "pattern" object which is stored in the patterns list?  
Many thanks,
Karen

**Comment by muhligs** [comment]
HI Karen, 
The pattern list is a list object that contains state automata data for the 7-mer motifs. 
Here is an example for the first 7-mer AAAAAAA:
[[1]]
$pattern
[1] "AAAAAAA"

$matrix
  A C G T
1 1 3 3 3
2 4 3 3 3
3 6 3 3 3
4 7 3 3 3
5 2 3 3 3
6 8 3 3 3
7 1 3 3 3
8 5 3 3 3

$startState
[1] 3

$endState
[1] 1

$matrix.di
    A  C  G  T
1A 1A 3C 3G 3T
2A 4A 3C 3G 3T
3C 6A 3C 3G 3T
3G 6A 3C 3G 3T
3T 6A 3C 3G 3T
4A 7A 3C 3G 3T
5A 2A 3C 3G 3T
6A 8A 3C 3G 3T
7A 1A 3C 3G 3T
8A 5A 3C 3G 3T

attr(,"class")
[1] "pattern"

The use of these are explained in more detail in this paper:
https://almob.biomedcentral.com/articles/10.1186/s13015-018-0135-2

But briefly, they are used to work out a transition probability matrix that is used to calculate the probability of seeing the motif in a given sequence. This is an integral part of the way miReact calculates enrichment of motif occurrences along a ranked list of UTR sequences. 

Inspired by your question, I will soon start making a vignette that explains how to make a pattern list from scratch, but basically it only involves loading the 'Regmex' package and running:

# define motifs
motifs <- Regmex::all.mers(4) # this simply makes all 4-mers from "AAAA" to "TTTT" in a vector

# make a pattern object of the first motif
Regmex:::pat.con(motifs[1])

# make pattern list of all the motifs
pattern.list <- lapply(motifs, Regmex:::pat.con)
pattern.list[[1]]

$pattern
[1] "AAAA"

$matrix
  A C G T
1 5 3 3 3
2 4 3 3 3
3 1 3 3 3
4 4 3 3 3
5 2 3 3 3

$startState
[1] 3

$endState
[1] 4

$matrix.di
    A  C  G  T
1A 5A 3C 3G 3T
2A 4A 3C 3G 3T
3C 1A 3C 3G 3T
3G 1A 3C 3G 3T
3T 1A 3C 3G 3T
4A 4A 3C 3G 3T
5A 2A 3C 3G 3T

attr(,"class")
[1] "pattern"

Hope this clarified things :)

Best,

Morten

**Comment by kapka2** [comment]
This clarifies.  Thanks very much.

**Comment by muhligs** [comment]
Closing this issue.
