### ISSUE TITLE
Issue in running miReact

### ISSUE THREAD

**Issue by GraziaMarini** [muhligs/miReact#7]
Hi!

First of all thank you for this tool! I am not an expert but I would like to use it on my data (skin human keratynocites) and I am not able to do it...

I downloaded the motif probability files from Synapse and I put them in the motif.models folder
Then I prepared my  own expression data set (13307 genes, 1614 cells) and I put it in the data folder

So I used these commands to generate the output file:

    - source ("~/miReact/code/mireact.R")
    - efile <- "~/miReact/data/MeP_mireact_exp.rds"
    - mireact(exp=efile, species="hs", motifs=7, seq.type="utr3", out.file= "~/miReact/data/mirnaActivity_MeP_K82.rds", out.meonly=T, install.dir = "~/miReact")

After running them, I have this message on RStudio:

_creating directory:  /home/grazia/miReact/o2022-06-2212:20:09 
[1] "Follow progress in /home/grazia/miReact/o2022-06-2212:20:09/Rscript-[jobid].out"_

So no error in R but the whole process fails because I obtain only a new folder with 3 files 

    - e.RData (I obtain this error when I try to open it:
      Error: bad restore file magic  number (file may be corrupted) -- no data loaded)
    - runparameters.RData
    - sbatch.script
 
and no Rscript-[processID].out or my output file in the data folder.

Do you have any suggestion?

Thank you and have a good day!

**Comment by muhligs** [comment]
Hi Grazia,

Can you try to run 
e <- readRDS("/path/to/e.Rdata")
To see that it loads ok. 

Also, can you post the content of the sbatch.script

**Comment by GraziaMarini** [comment]
Hi!

So I have tried to open the e.Rdata file and it contains the exact same information of the starting efile (so a matrix of 13,307 entries, 1614 total column containing the same values of the efile).

And this is the content of the sbatch.script:

#!/bin/sh
#SBATCH --nodes 1
#SBATCH -c 1
#SBATCH --time 48:00:00
#SBATCH --mem 128g
#SBATCH --job-name Rscript

[ $SLURM_PROCID -ne 0 ] && exit 0
cd  /home/grazia/miReact/o2022-06-2212:20:09 
Rscript --vanilla ../code/wrapper3.R

**Comment by muhligs** [comment]
Hi again, 
We need to locate the output logs in order to make progress. This may be setup differently on different systems, and thus the message:
'Follow progress in /home/grazia/miReact/o2022-06-2212:20:09/Rscript-[jobid].out'
may not apply to your system. Maybe these outputs ar put somewhere special, e.g. your home?

**Comment by muhligs** [comment]
Or, perhaps the slurm script is not started at all. 
Try changing this line in mireact.R:
waste <- system("sbatch sbatch.script", ignore.stdout = T, ignore.stderr = T)
to
waste <- system("sbatch sbatch.script", ignore.stdout = F, ignore.stderr = F)
print(waste)
and see what is printed on the terminal and in the content of waste

**Comment by GraziaMarini** [comment]
Hi!

I will try as soon as possible (probably next week) and I will give you updates, thank you!

**Comment by GraziaMarini** [comment]
Hi! 

I have not tried your suggestion so far but I was also wondering if it could be possible to obtain a miReact version in PBS instead of SLURM. Thank you again!

**Comment by muhligs** [comment]
Hi Grazia, 
I am not familiar with PBS, but the slurm scripts are simply written from R via the sink() command and started with the system() command, so I think it would be trivial to change the R scripts accordingly.

**Comment by GraziaMarini** [comment]
Hi again!

I found out that the problem is in our slurm configuration so we would like to try to run it on a local computer (our dataset has about 1000 cells, so it should not be so big...). I have tried to follow your suggestion here 
 https://github.com/muhligs/miReact/issues/4 and, as LGGray I obtain a mailmessage.txt with this text

```
exp ~/Desktop/miReact/data/MeP_mireact_exp.rds
species hs
seq.type utr3
out.file ~/Desktop/miReact/data/mirnaActivity_MeP_K82.rds
out.meonly TRUE
verbose FALSE
install.dir ~/Desktop/miReact
mail NULL
memory 128g
wt 48:00:00
tarbaserun FALSE
wd /Users/admin/Desktop/miReact/o2022-06-3010:07:36
runparameters$motifs: 7-mers
```
and I have tried to follow your suggestion about wrapper3 (I don't see any prints to the console) putting sink(statments.txt) before the line 
`cat("\nLoading expression data...\n")`
and sink() after the line 
`sco<- list(exp=e)`

and obtaining a statments.txt file with this content

```
Loading expression data...
2022-06-30 10:15:25 
```
I don't understand the problem...

Thanks!

**Comment by muhligs** [comment]
You can try to put sink() at the very end of wrapper3 (instead) then you will get all print statements in the file, and maybe get to know where it fails.

**Comment by GraziaMarini** [comment]
Ok I did it and I obtain this:

```
running addSeqs...
2022-06-30 16:16:58 
genes in exp matrix:  13307 
Samples/cells in exp matrix:  1614 
Chosen identifier:  Ensembl gene ID .
genes not found:  0 
genes found:  13307 
reducing expression matrix to contain genes with sequence data.
expression matrix now contains  13307  genes with  13307  names.
adding $seqs to output object.
adding $seqslist (sequence stats) to output object.
Finished.
Done
2022-06-30 16:17:00 

running addMotifs...
2022-06-30 16:17:00
adding motif models.
16384  motif models added.
```
but no output file is generated...

**Comment by muhligs** [comment]
It shold continue immideately with writing:
running addMotifs...

Did that not happen?

**Comment by GraziaMarini** [comment]
Yes, I am sorry I corrected the previous comment because it was uncomplete

**Comment by muhligs** [comment]
It looks like it has not finished yet. It should either produce error statements or write additional statements from the R scripts in the sink file. 
You can look in addMotifs.R and subsequently addMotifExpression.R to see what you can expect to be written in the sink file.

**Comment by GraziaMarini** [comment]
Hi!

In the end I was able to work it out locally, thanks for your suggestion. The problem was in one of the files downloaded from Synapse but after re-downloading it everything was ok. 

Now, have the file with miRNA activities but I have another question: what does it mean to obtain a negative activity value? It is not clear for me from the paper...thank you again for your support!

Grazia

**Comment by muhligs** [comment]
Hi Garzia, 
You should regard the activity values as a relative measure, so negative values means lower activity than in non-negative samples. If you se a subset of samples with high negative values and the majority of samples having values around zero, it could be because this miRNA in general has high activity in the 'zero' samples and low activity in the sub set. Think of the zero point sort of as the median activity and values high or low as 'higher' or 'lower' than that.

**Comment by GraziaMarini** [comment]
Thanks!

Now I'm in the final step: how to connect the sequence that I obtain with a specific miRNA? 

I see that for miR-122-5p in Mus Musculus you obtain 

**ACACTCC** 

while the mature miRNA sequence, downloaded from TarBase, is

**>hsa-miR-122-5p MIMAT0000421 Homo sapiens miR-122-5p UGGAGUGUGACAAUGGUGUUUG**

so for every output sequence I have to do the reverse complement (UGUGAGG) and then I have to read it from right to left (GGAGUGU) and it should be equal to the sequence downloaded from miRBase, starting from position n2? Is that correct?

Thanks again,

Grazia

**Comment by muhligs** [comment]
Sorry for the late reply. 
Yeah, sort of. I would say: Take bases from n2 to n8. 'Translate' to DNA (GGAGTGT). Reverse-complement (ACACTCC). 
Since the target UTRs are all DNA sequences, that is how the enriched 7-mer would look like in the matrix. 
Best,
Morten

**Comment by muhligs** [comment]
I am closing the issue.
